__Q: What are the different data structures used in TensorFlow? Give some examples.__

A: TensorFlow primarily uses two main data structures:

Tensors: Tensors are the fundamental building blocks of TensorFlow. They are multi-dimensional arrays and represent the data flowing through the computational graph. Tensors can be scalar (0-dimensional), vectors (1-dimensional), matrices (2-dimensional), or have higher dimensions. Examples of tensors include:

Scalar: [5]
Vector: [1, 2, 3]
Matrix: [[1, 2], [3, 4]]
Graphs: TensorFlow uses a computation graph to represent the mathematical operations performed on tensors. The graph defines the flow of data and operations that take tensors as input and produce tensors as output.

__Q: How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.__

A: In TensorFlow, constants and variables are two different types of tensors:

Constants: Constants are tensors whose value cannot be changed during the execution of the graph. They are typically used to represent fixed values or hyperparameters. Once defined, their value remains constant throughout the graph's execution. Example:


import tensorflow as tf

# Creating a TensorFlow constant
constant_tensor = tf.constant([1, 2, 3])
Variables: Variables are tensors that can change their value during the execution of the graph. They are used to hold trainable parameters, such as weights and biases, that are updated during the training process. Example:

import tensorflow as tf

# Creating a TensorFlow variable
initial_values = tf.random.normal(shape=(3,))
variable_tensor = tf.Variable(initial_values)

__Q: Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.__

A: In TensorFlow, matrix addition, multiplication, and element-wise operations are performed using tensor operations:

Matrix Addition: To add two matrices, the tf.add() function is used. Both matrices must have the same shape.

import tensorflow as tf

# Matrix Addition
matrix_A = tf.constant([[1, 2], [3, 4]])
matrix_B = tf.constant([[5, 6], [7, 8]])
result_addition = tf.add(matrix_A, matrix_B)
Matrix Multiplication: To multiply two matrices, the tf.matmul() function or the @ operator can be used.


import tensorflow as tf

# Matrix Multiplication
matrix_A = tf.constant([[1, 2], [3, 4]])
matrix_B = tf.constant([[5, 6], [7, 8]])
result_multiplication = tf.matmul(matrix_A, matrix_B)
# Alternatively: result_multiplication = matrix_A @ matrix_B
Element-wise Operations: Element-wise operations perform operations element by element in two tensors of the same shape. Common element-wise operations include addition (tf.add()), subtraction (tf.subtract()), multiplication (tf.multiply()), and division (tf.divide()).

import tensorflow as tf

# Element-wise operations
tensor_A = tf.constant([1, 2, 3])
tensor_B = tf.constant([4, 5, 6])
result_element_wise_addition = tf.add(tensor_A, tensor_B)
result_element_wise_subtraction = tf.subtract(tensor_A, tensor_B)
result_element_wise_multiplication = tf.multiply(tensor_A, tensor_B)
result_element_wise_division = tf.divide(tensor_A, tensor_B)
In TensorFlow, these operations are executed as part of a computational graph, enabling efficient and optimized calculations on tensors.

In [1]:
import tensorflow as tf

# Task Tc: Create a normal matrix A with dimensions 2x2
matrix_A = tf.random.normal(shape=(2, 2), mean=0, stddev=1)
print("Matrix A:")
print(matrix_A.numpy())

# Task Cc: Create a Gaussian matrix B with dimensions 2x2
matrix_B = tf.random.truncated_normal(shape=(2, 2), mean=0, stddev=1)
print("\nMatrix B:")
print(matrix_B.numpy())

# Task =c: Create a matrix C with dimensions 2x2, drawn from a normal distribution with mean=2 and stddev=0.x
matrix_C = tf.random.normal(shape=(2, 2), mean=2, stddev=0.1)
print("\nMatrix C:")
print(matrix_C.numpy())

# Task ~c: Perform matrix addition between matrix A and matrix B, store the result in matrix D
matrix_D = tf.add(matrix_A, matrix_B)
print("\nMatrix D (result of A + B):")
print(matrix_D.numpy())

# Task wc: Perform matrix multiplication between matrix C and matrix D, store the result in matrix E
matrix_E = tf.matmul(matrix_C, matrix_D)
print("\nMatrix E (result of C * D):")
print(matrix_E.numpy())

Matrix A:
[[ 0.5535151  -0.96056587]
 [ 1.3661344  -1.4548182 ]]

Matrix B:
[[ 0.28496647 -1.2424446 ]
 [ 0.43053865 -0.53638697]]

Matrix C:
[[1.8541374 1.9708749]
 [2.1641717 2.0134406]]

Matrix D (result of A + B):
[[ 0.83848155 -2.2030106 ]
 [ 1.796673   -1.9912052 ]]

Matrix E (result of C * D):
[[ 5.095678  -8.009101 ]
 [ 5.4321127 -8.776867 ]]


In [2]:

# Task Tc: Create a matrix F with dimensions 2x2, initialized with random values using random_uniform
matrix_F = tf.random.uniform(shape=(2, 2))
print("Matrix F:")
print(matrix_F.numpy())

# Task Cc: Calculate the transpose of matrix F and store the result in matrix G
matrix_G = tf.transpose(matrix_F)
print("\nMatrix G (transpose of F):")
print(matrix_G.numpy())

# Task =c: Calculate the element-wise exponential of matrix F and store the result in matrix H
matrix_H = tf.exp(matrix_F)
print("\nMatrix H (element-wise exponential of F):")
print(matrix_H.numpy())

# Task ~c: Create a matrix I by concatenating matrix F and matrix G horizontally
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)
print("\nMatrix I (concatenation of F and G horizontally):")
print(matrix_I.numpy())

# Task wc: Create a matrix J by concatenating matrix F and matrix H vertically
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)
print("\nMatrix J (concatenation of F and H vertically):")
print(matrix_J.numpy())

Matrix F:
[[0.6900246  0.482067  ]
 [0.60584843 0.87183213]]

Matrix G (transpose of F):
[[0.6900246  0.60584843]
 [0.482067   0.87183213]]

Matrix H (element-wise exponential of F):
[[1.9937646 1.6194183]
 [1.8328066 2.391288 ]]

Matrix I (concatenation of F and G horizontally):
[[0.6900246  0.482067   0.6900246  0.60584843]
 [0.60584843 0.87183213 0.482067   0.87183213]]

Matrix J (concatenation of F and H vertically):
[[0.6900246  0.482067  ]
 [0.60584843 0.87183213]
 [1.9937646  1.6194183 ]
 [1.8328066  2.391288  ]]
